### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Marbyun** [farukalampro/ai-chatbot-using-Langchain-Pinecone#1]
hi i just clone and run your code using your data, already set my dimensions to 384 in pinecone and get error 

`IndexError: list index out of range`

can you help to this error?

and can we adjust the dimensions?

**Comment by farukalamai** [comment]
When you are creating the index in Pinecone, did you set the index name as "langchain-chatbot"?

**Comment by farukalamai** [comment]
Check my updated README file :)
